name: robertawilliams
favicon: null
layout_spectrum: 0.9615170634351671
typography_spectrum: 0.00812812545336783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#000407'
    - '#8c705b'
    - '#9bb4d8'
    - '#0d3b70'
  brandStrength: 0.625
  lightness: 0.7615051437169313
  saturation: 0.10972028714604676
  rhythmicContrast: 0.2933171179611236
purpose: []
