name: robertawilliams
favicon: null
layout_spectrum: 0.9615170634351671
typography_spectrum: 0.00812812545336783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6262210649438202
  lightness: 0.7615051437169313
  saturation: 0.10972028714604676
  rhythmicContrast: 0.2933171179611236
purpose: []
